version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: penciluser
      POSTGRES_PASSWORD: pencilsenha
      POSTGRES_DB: pencil
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
